### ISSUE TITLE
Purchases without billing data show errors

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-invoices#15]
If you enable taxes but then sell a free download, it won't collect the user's address (because it is free and taxes aren't charged on free products). 

However, this leaves the payment without billing data (address etc). 

When the customer goes to generate an invoice for this free product they see errors:

```
<br /><b>Notice</b>:  Undefined index: address in <b>/Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/edd-invoices/views/form.php</b> on line <b>18</b><br />
```

<img width="576" alt="screen shot 2017-04-04 at 2 32 06 pm" src="https://cloud.githubusercontent.com/assets/1638128/24672701/b1139376-1943-11e7-9635-59303372b97a.png">

If, for any reason, the payment does not have billing data saved, it should fallback to use the customer's address/data. If that data doesn't exist, it should output nothing.

**Comment by pippinsplugins** [comment]
PR https://github.com/easydigitaldownloads/edd-invoices/pull/16

**Comment by pderksen** [comment]
FYI in my case it isn't free orders. It's simply because I don't require the billing address for Stripe credit card payments.

**Comment by cklosowski** [comment]
:+1: Thanks @pderksen I'm testing this now

**Comment by cklosowski** [comment]
Ok `issue/15` is ready for testing.

Easiest way to test is on `master` use Test Purchase with no taxes...and then try and generate an invoice.

**Comment by pippinsplugins** [comment]
Works well for me, merge.
